### ISSUE TITLE
Socket_Toolkit: resolve the admin rights issue

### ISSUE THREAD

**Issue by adecler** [BHoM/Socket_Toolkit#21]
### This issue has been archived 

Historic issue archive can be found [here](https://burohappold.sharepoint.com/sites/BHoM/01_Master%20File/Forms/AllItems.aspx?id=%2Fsites%2FBHoM%2F01_Master%20File%2F999_BHoM_GitHub_History_Archive)

**Comment by awakeman** [comment]
This has come back up a couple of times last week. see: BHoM/Excel_Toolkit#87. 

I believe the issue is that we are listening on all addresses and not just localhost. Obviously we will want an option to open the port more widely for actual communications over a network but 9 times out of 10 people want only a localhost connection.

https://github.com/BHoM/Socket_Toolkit/blob/d817b65b87eee7e6edf6abaa285130d1f38f8a81/Socket_Adapter/Udp/SocketServer_Udp.cs#L71

https://github.com/BHoM/Socket_Toolkit/blob/d817b65b87eee7e6edf6abaa285130d1f38f8a81/Socket_Adapter/Tcp/SocketServer_Tcp.cs#L75

Its a little hard to test because I don't know how to revoke the permissions and try again.
